Add dataset directory stream method to dataset manager
VEuPathDB/vdi-component-s3 pull request #1
Opened 2023-04-19 21:24 UTC by dmgaldi

## Overview
* Adding `streamAllDatasets(): Stream<DatasetDirectory>` to DatasetManager`
* Added an eagerly loaded implementation of `DatasetDirectory` since we have access to all objects in S3
* In support of above, added alternate constructors to all `*FileImpl` classes that takes an object instead of s3 location info

## Testing
Just unit tests for now. There's some slightly tricky logic to group the dataset files together that could possibly be simplified?

2023-04-25 17:38 UTC, Foxcapades requested changes
Looks good except a likely copy/paste issue in [DatasetDeleteFlagFileImpl.kt](https://github.com/VEuPathDB/vdi-component-s3/pull/1/files#diff-8c181d8c4776680a4e8ab36251648e758ab724746aba84a24a7d1de02e27f2fe)

2023-04-25 17:38 UTC, Foxcapades commented on src/main/kotlin/org/veupathdb/vdi/lib/s3/datasets/DatasetDeleteFlagFileImpl.kt
> +        if (s3Object.baseName !== S3Paths.SHARE_OFFER_FILE_NAME) {
Why is the delete file looking for `SHARE_OFFER_FILE_NAME`, shouldn't it be the delete flag file?

2023-04-25 17:38 UTC, Foxcapades commented on src/main/kotlin/org/veupathdb/vdi/lib/s3/datasets/DatasetDirectoryImpl.kt
> +import java.time.OffsetDateTime
Nitpick: Unnecessary import?

2023-04-25 17:38 UTC, Foxcapades commented on src/main/kotlin/org/veupathdb/vdi/lib/s3/datasets/DatasetManager.kt
> +        val currDatasetID = currDatasetIDs.second
Not suggesting a change, just pointing out a handy kotlin thing you can do here: unpacking the returned pair by doing:
```kotlin
val (currUserID, currDatasetID) = datasetIdFromS3Object(stagedObjects.first())
```

this also works for data classes and classes that implement the appropriate operator functions for unpacking

2023-04-25 18:50 UTC, dmgaldi commented on src/main/kotlin/org/veupathdb/vdi/lib/s3/datasets/DatasetManager.kt
> +        val currDatasetID = currDatasetIDs.second
I tried this and missed the parentheses! I thought it was just wishful thinking

2023-04-25 18:52 UTC, dmgaldi commented on src/main/kotlin/org/veupathdb/vdi/lib/s3/datasets/DatasetDeleteFlagFileImpl.kt
> +        if (s3Object.baseName !== S3Paths.SHARE_OFFER_FILE_NAME) {
Oops, I'll add a unit test with a delete flag.

2023-04-26 13:51 UTC, Foxcapades approved these changes

2023-04-27 15:15 UTC, merged